import type {
  GhidraAnalysisOutput,
  GhidraFunctionSummary,
  HookParameter,
  HookTemplate,
} from './types';
import { ToolError } from '@errors/ToolError';

type HookCategory =
  | 'jni'
  | 'aes'
  | 'md5'
  | 'sha'
  | 'rsa'
  | 'base64'
  | 'network'
  | 'file-io'
  | 'string'
  | 'obfuscation'
  | 'unknown';

export class HookCodeGenerator {
  generateHooks(input: GhidraAnalysisOutput): HookTemplate[] {
    const templates: HookTemplate[] = [];

    for (const fn of input.functions) {
      const category = this.classifyFunction(fn, input);
      if (category === 'unknown') {
        continue;
      }

      templates.push({
        functionName: fn.name,
        description: this.describeCategory(category, input),
        hookCode: this.buildHookCode(fn, category),
        parameters: this.buildParameters(fn),
      });
    }

    return templates;
  }

  exportScript(templates: HookTemplate[], format: string): string {
    if (format !== 'frida') {
      throw new ToolError(
        'VALIDATION',
        `Unsupported export format: "${format}". Only "frida" is supported.`,
      );
    }

    const lines = [
      '// Frida hook script',
      '// auto-generated by HookCodeGenerator',
      `// Hook count: ${templates.length}`,
      '',
    ];

    for (const template of templates) {
      lines.push(`// ${template.functionName}: ${template.description}`);
      lines.push(template.hookCode);
      lines.push('');
    }

    return lines.join('\n');
  }

  private classifyFunction(fn: GhidraFunctionSummary, input: GhidraAnalysisOutput): HookCategory {
    const name = fn.name.toLowerCase();
    const imports = input.imports.map((entry) => entry.toLowerCase());
    const strings = input.strings.map((entry) => entry.toLowerCase());

    if (fn.name.startsWith('Java_')) {
      return 'jni';
    }

    if (name.includes('aes')) {
      return 'aes';
    }

    if (name.includes('md5')) {
      return 'md5';
    }

    if (name.includes('sha')) {
      return 'sha';
    }

    if (name.includes('rsa')) {
      return 'rsa';
    }

    if (name.includes('base64')) {
      return 'base64';
    }

    if (
      name.includes('send') ||
      name.includes('recv') ||
      name.includes('socket') ||
      name.includes('http')
    ) {
      return 'network';
    }

    if (
      name.includes('open') ||
      name.includes('read') ||
      name.includes('write') ||
      name.includes('fopen')
    ) {
      return 'file-io';
    }

    if (
      (name.includes('decrypt') || name.includes('encrypt')) &&
      strings.some((entry) => entry.includes('obfuscation') || entry.includes('encryption'))
    ) {
      return 'obfuscation';
    }

    if (
      name.includes('memcpy') ||
      name.includes('strcpy') ||
      name.includes('memmove') ||
      name.includes('string')
    ) {
      return 'string';
    }

    if (imports.some((entry) => entry.includes('aes'))) {
      return 'aes';
    }

    return 'unknown';
  }

  private describeCategory(category: HookCategory, input: GhidraAnalysisOutput): string {
    switch (category) {
      case 'jni':
        return 'JNI bridge hook for Java/native boundary inspection';
      case 'aes':
        return 'AES crypto hook for key/plaintext capture';
      case 'md5':
        return 'MD5 crypto hook for digest inspection';
      case 'sha':
        return 'SHA crypto hook for digest inspection';
      case 'rsa':
        return 'RSA crypto hook for key operation tracing';
      case 'base64':
        return 'Base64 transform hook for encoded data tracing';
      case 'network':
        return 'Network hook for request and response body tracing';
      case 'file-io':
        return 'File I/O hook for filesystem access tracing';
      case 'string':
        return 'String operation hook for buffer tracing';
      case 'obfuscation':
        return input.strings.some((entry) => entry.toLowerCase().includes('obfuscation'))
          ? 'Potential obfuscation hook for runtime string decryption tracing'
          : 'Potential obfuscation hook';
      case 'unknown':
        return 'Unknown hook';
    }
  }

  private buildHookCode(fn: GhidraFunctionSummary, category: HookCategory): string {
    if (category === 'jni') {
      return [
        'Java.perform(function () {',
        `  const target = ptr("${fn.address}");`,
        '  Interceptor.attach(target, {',
        '    onEnter(args) {',
        `      console.log("[jni] ${fn.name}");`,
        '    },',
        '  });',
        '});',
      ].join('\n');
    }

    const extraLine =
      category === 'aes' ||
      category === 'md5' ||
      category === 'sha' ||
      category === 'rsa' ||
      category === 'base64'
        ? '      console.log(hexdump(args[0]));'
        : '      console.log("[trace] entering");';
    const targetName = fn.name.replace(/[^A-Za-z0-9_]/g, '_');

    return [
      `const target_${targetName} = ptr("${fn.address}");`,
      `Interceptor.attach(target_${targetName}, {`,
      '  onEnter(args) {',
      `    console.log("[hook] ${fn.name}");`,
      extraLine,
      '  },',
      '});',
    ].join('\n');
  }

  private buildParameters(fn: GhidraFunctionSummary): HookParameter[] {
    if (fn.parameters.length > 0) {
      return fn.parameters.map((parameter, index) => ({
        name: parameter.name || `arg${index}`,
        type: parameter.type || 'pointer',
        description: `Captured parameter ${index}`,
      }));
    }

    return [
      {
        name: 'arg0',
        type: 'pointer',
        description: 'Captured parameter 0',
      },
    ];
  }
}
